analyze TABLE archiv compute statistics;
analyze TABLE autor compute statistics;
analyze TABLE ctenar compute statistics;
analyze TABLE hodnoceni compute statistics;
analyze TABLE kniha compute statistics;
analyze TABLE nakladatelstvi compute statistics;
analyze TABLE napsal compute statistics;
analyze TABLE vypujcky compute statistics;
analyze TABLE zanr compute statistics;